---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - пользователь должен иметь возможность регистрироваться
  - в целях соблюдения законодательства пользователь должен дать согласие на обработку персональных данных
  - пользователь должен иметь возможность зайти в свою учетную запись
  - пользователь должен иметь возможность просматривать свои заказы, их статус
  - при помещении товара в корзину, пользователь должен иметь возможность ввести количество товара
  - при просмотре корзины, пользователь должен иметь возможность редактировать товары и их количество
  - при изменении количества товара в корзине, сумма должна пересчитываться автоматически
  - пользователь должен иметь возможность оплатить заказ картой  
